#############################################################################
# Makefile for building: build/release/WebGuitarProStore
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  QWebGuitarProStore.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile QWebGuitarProStore.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -Isrc -I/home/vagrant/tools/qt-6.4.2/x86_64/include -I/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets -I/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui -I/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore -Ibuild/release/.moc -I/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/linux-g++-64
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = WebGuitarProStore1.0.0
DISTDIR = /projects/VS_WebGuitarPro_Store/build/release/.obj/WebGuitarProStore1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/vagrant/tools/qt-6.4.2/x86_64/lib -Wl,-rpath-link,/home/vagrant/tools/qt-6.4.2/x86_64/lib
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 /home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Widgets.so /home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Gui.so /home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/release/.obj/

####### Files

SOURCES       = src/main.cpp \
		src/Widget/SystemTrayMenu.cpp build/release/.qrc/qrc_WebGuitarProStore.cpp \
		build/release/.moc/moc_SystemTrayMenu.cpp
OBJECTS       = build/release/.obj/main.o \
		build/release/.obj/SystemTrayMenu.o \
		build/release/.obj/qrc_WebGuitarProStore.o \
		build/release/.obj/moc_SystemTrayMenu.o
DIST          = /home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/spec_pre.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/unix.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/linux.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/sanitize.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/gcc-base.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/gcc-base-unix.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/g++-base.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/g++-unix.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/qconfig.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_ext_libjpeg.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_charts.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_chartsqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_coap.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_coap_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core5compat.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designer.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_gui.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_help.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_httpserver.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_httpserver_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsanimation.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssettings.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_languageserver_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_linguist.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_mqtt.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_mqtt_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_network.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opcua.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opcua_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcore.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3d.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3deffects.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensorsquick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_shadertools.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_spatialaudio.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sql.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachine.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svg.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_tools_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webview.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webviewquick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt_functions.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt_config.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/linux-g++-64/qmake.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/exclusive_builds.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/toolchain.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/default_pre.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resolve_config.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/default_post.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/warn_on.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resources_functions.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resources.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/moc.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/unix/opengl.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/uic.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/unix/thread.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qmake_use.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/file_copies.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/testcase_targets.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/exceptions.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/yacc.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/lex.prf \
		QWebGuitarProStore.pro src/Widget/SystemTrayMenu.h src/main.cpp \
		src/Widget/SystemTrayMenu.cpp
QMAKE_TARGET  = WebGuitarProStore
DESTDIR       = build/release/
TARGET        = build/release/WebGuitarProStore


first: all
####### Build rules

build/release/WebGuitarProStore:  $(OBJECTS)  
	@test -d build/release/ || mkdir -p build/release/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QWebGuitarProStore.pro /home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/linux-g++-64/qmake.conf /home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/spec_pre.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/unix.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/linux.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/sanitize.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/gcc-base.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/gcc-base-unix.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/g++-base.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/g++-unix.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/qconfig.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_ext_libjpeg.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_charts.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_chartsqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_coap.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_coap_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core5compat.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designer.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_gui.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_help.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_httpserver.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_httpserver_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsanimation.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssettings.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_languageserver_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_linguist.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_mqtt.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_mqtt_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_network.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opcua.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opcua_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcore.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3d.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3deffects.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensorsquick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_shadertools.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_spatialaudio.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sql.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachine.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svg.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_tools_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webview.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webviewquick.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xml.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt_functions.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt_config.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/linux-g++-64/qmake.conf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/exclusive_builds.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/toolchain.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/default_pre.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resolve_config.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/default_post.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/warn_on.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resources_functions.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resources.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/moc.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/unix/opengl.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/uic.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/unix/thread.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qmake_use.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/file_copies.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/testcase_targets.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/exceptions.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/yacc.prf \
		/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/lex.prf \
		QWebGuitarProStore.pro \
		WebGuitarProStore.qrc \
		/home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Widgets.prl \
		/home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Gui.prl \
		/home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile QWebGuitarProStore.pro
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/spec_pre.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/unix.conf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/linux.conf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/sanitize.conf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/gcc-base.conf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/gcc-base-unix.conf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/g++-base.conf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/common/g++-unix.conf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/qconfig.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_ext_libjpeg.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3drender.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_charts.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_chartsqml.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_coap.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_coap_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core5compat.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core5compat_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_core_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_dbus.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_declarativeopcua.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designer.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_gui.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_help.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_help_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_httpserver.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_httpserver_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_jpeg_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsanimation.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssettings.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssettings_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssharedimage.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_languageserver_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_linguist.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_linguist_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_mqtt.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_mqtt_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_network.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_network_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_nfc.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opcua.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opcua_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opengl.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_openglwidgets.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioning.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qml.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcore.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmldom_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlintegration.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3d.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3d_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3deffects.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticles.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysics.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dutils.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicklayouts.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktimeline.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_repparser.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxml.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxmlqml.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensors.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensorsquick.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialport.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_shadertools.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_shadertools_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_spatialaudio.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sql.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachine.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachine_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachineqml.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svg.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svgwidgets.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_testlib.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_tools_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uitools.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_websockets.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webview.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webviewquick.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_webviewquick_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_widgets.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xml.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt_functions.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt_config.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/linux-g++-64/qmake.conf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/exclusive_builds.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/toolchain.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/default_pre.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resolve_config.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/default_post.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/warn_on.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qt.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resources_functions.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/resources.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/moc.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/unix/opengl.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/uic.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/unix/thread.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/qmake_use.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/file_copies.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/testcase_targets.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/exceptions.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/yacc.prf:
/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/lex.prf:
QWebGuitarProStore.pro:
WebGuitarProStore.qrc:
/home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Widgets.prl:
/home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Gui.prl:
/home/vagrant/tools/qt-6.4.2/x86_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QWebGuitarProStore.pro

qmake_all: FORCE


all: Makefile build/release/WebGuitarProStore

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents WebGuitarProStore.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Widget/SystemTrayMenu.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Widget/SystemTrayMenu.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/release/.qrc/qrc_WebGuitarProStore.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/release/.qrc/qrc_WebGuitarProStore.cpp
build/release/.qrc/qrc_WebGuitarProStore.cpp: WebGuitarProStore.qrc \
		/home/vagrant/tools/qt-6.4.2/x86_64/libexec/rcc \
		VERSION \
		Resources/icons/logo.png
	/home/vagrant/tools/qt-6.4.2/x86_64/libexec/rcc -name WebGuitarProStore WebGuitarProStore.qrc -o build/release/.qrc/qrc_WebGuitarProStore.cpp

compiler_moc_predefs_make_all: build/release/.moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/release/.moc/moc_predefs.h
build/release/.moc/moc_predefs.h: /home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/data/dummy.cpp
	g++ -m64 -pipe -O2 -Wall -Wextra -fPIC -dM -E -o build/release/.moc/moc_predefs.h /home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/release/.moc/moc_SystemTrayMenu.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/release/.moc/moc_SystemTrayMenu.cpp
build/release/.moc/moc_SystemTrayMenu.cpp: src/Widget/SystemTrayMenu.h \
		build/release/.moc/moc_predefs.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/libexec/moc
	/home/vagrant/tools/qt-6.4.2/x86_64/libexec/moc $(DEFINES) --include /projects/VS_WebGuitarPro_Store/build/release/.moc/moc_predefs.h -I/home/vagrant/tools/qt-6.4.2/x86_64/mkspecs/linux-g++-64 -I/projects/VS_WebGuitarPro_Store -I/projects/VS_WebGuitarPro_Store/src -I/home/vagrant/tools/qt-6.4.2/x86_64/include -I/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets -I/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui -I/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Widget/SystemTrayMenu.h -o build/release/.moc/moc_SystemTrayMenu.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/release/.obj/main.o: src/main.cpp /home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/QApplication \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/qapplication.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qtguiglobal.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qglobal.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qconfig-bootstrapped.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qconfig.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qtcore-config.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qtconfigmacros.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qtcoreexports.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qsystemdetection.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qprocessordetection.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcompilerdetection.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qtypeinfo.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcontainerfwd.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qsysinfo.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qlogging.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qflags.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcompare_impl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qatomic.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qbasicatomic.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qatomic_bootstrap.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qgenericatomic.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qatomic_cxx11.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qglobalstatic.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qnumeric.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qversiontagging.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qforeach.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qtgui-config.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qtguiexports.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/qtwidgets-config.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/qtwidgetsexports.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcoreapplication.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstring.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qchar.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringview.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qbytearray.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qrefcount.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qnamespace.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qtmetamacros.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qarraydata.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qpair.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qarraydatapointer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qarraydataops.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcontainertools_impl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qbytearrayalgorithms.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qbytearrayview.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringfwd.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringliteral.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringalgorithms.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qanystringview.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qutf8stringview.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringtokenizer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringbuilder.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcoreevent.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qobjectdefs.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qobjectdefs_impl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qeventloop.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qobject.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qlist.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qhashfunctions.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qiterator.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qbytearraylist.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringlist.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qalgorithms.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringmatcher.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qscopedpointer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qmetatype.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcompare.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qscopeguard.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qdatastream.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qiodevicebase.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qiterable.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qmetacontainer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcontainerinfo.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qtaggedpointer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qmath.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qobject_impl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qbindingstorage.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qnativeinterface.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qdebug.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qtextstream.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qstringconverter_base.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcontiguouscache.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qsharedpointer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qshareddata.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qsharedpointer_impl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qmap.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qshareddata_impl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qset.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qhash.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qvarlengtharray.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qcoreapplication_platform.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qjnitypes.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qfuture.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qfutureinterface.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qmutex.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qtsan_impl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qresultstore.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qfuture_impl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qthreadpool.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qthread.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qdeadlinetimer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qelapsedtimer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qrunnable.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qexception.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qpointer.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qpromise.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qvariant.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qwindowdefs.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qwindowdefs_win.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qpoint.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qsize.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qmargins.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qcursor.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qbitmap.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qpixmap.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qpaintdevice.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qrect.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qcolor.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qrgb.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qrgba64.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qimage.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qpixelformat.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qtransform.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qpolygon.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qregion.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qline.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qguiapplication.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qinputmethod.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qlocale.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qguiapplication_platform.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/QDebug \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/QIcon \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qicon.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/QSystemTrayIcon \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/qsystemtrayicon.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/QMenu \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/qmenu.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/qwidget.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qaction.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qkeysequence.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qpalette.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qbrush.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qfont.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qfontmetrics.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qfontinfo.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtWidgets/qsizepolicy.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qevent.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qiodevice.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/qurl.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qeventpoint.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qvector2d.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qvectornd.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qpointingdevice.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qinputdevice.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/qscreen.h \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/QList \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/QObject \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/QRect \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/QSize \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtCore/QSizeF \
		/home/vagrant/tools/qt-6.4.2/x86_64/include/QtGui/QTransform \
		src/Widget/SystemTrayMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/main.o src/main.cpp

build/release/.obj/SystemTrayMenu.o: src/Widget/SystemTrayMenu.cpp src/Widget/SystemTrayMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/SystemTrayMenu.o src/Widget/SystemTrayMenu.cpp

build/release/.obj/qrc_WebGuitarProStore.o: build/release/.qrc/qrc_WebGuitarProStore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/qrc_WebGuitarProStore.o build/release/.qrc/qrc_WebGuitarProStore.cpp

build/release/.obj/moc_SystemTrayMenu.o: build/release/.moc/moc_SystemTrayMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/release/.obj/moc_SystemTrayMenu.o build/release/.moc/moc_SystemTrayMenu.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

